Fix the `ping` results
ipfs-inactive/js-ipfs-http-client pull request #556
Opened 2017-05-16 15:40 UTC by ngotchac

I've see cases where the `ping` response is in fact on 2 lines, the second one containing the Success (`false`), the Time and the Text. This happens for example if you try to ping your self.

2017-05-29 20:57 UTC, diasdavid commented
@Kubuxu any thoughts on why this happens?

2017-07-08 09:10 UTC, diasdavid commented
@ngotchac mind rebasing master onto this PR?

@Kubuxu thoughts?

2017-07-08 10:00 UTC, Kubuxu commented
It has happened because `ping` endpoint is ndjson streaming endpoing. The order of responses that can be received there are not part of the API.

What the code should do is parse the response as NDJSON (line by line) and look for `.Time != 0`.

2017-09-06 08:44 UTC, diasdavid commented
@ngotchac wanna follow up on this PR?

2017-10-09 11:00 UTC, Kubuxu requested changes
This isn't the right way to do it as API does not specify order of messages. See https://github.com/ipfs/js-ipfs-api/pull/556#issuecomment-313846598

(cleaning up my CR queue)

2018-03-25 02:54 UTC, closed without merging