fix: config get (#822)
ipfs-inactive/js-ipfs-http-client pull request #825
Opened 2018-08-03 10:30 UTC by hacdias

Fixes config.get by always returning an object and never a buffer. It can be a possible breaking change for those using js-ipfs-api with go-ipfs, but not with js-ipfs.

Ref.: https://github.com/ipfs/js-ipfs-api/issues/822

2018-08-04 12:51 UTC, hacdias commented
@diasdavid @alanshaw what do you think? 😄

2018-08-06 07:13 UTC, hacdias commented
[What interface says](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/CONFIG.md#configget).

2018-08-06 07:34 UTC, daviddias requested changes
Needs tests to make sure this doesn't break again.

2018-08-06 07:51 UTC, hacdias commented
@diasdavid

2018-08-06 10:55 UTC, alanshaw approved these changes

2018-08-06 14:15 UTC, merged