fix: handle peer-info validation errors
ipfs-inactive/js-ipfs-http-client pull request #887
Opened 2018-11-06 17:15 UTC by olizilla

BREAKING CHANGE. Previously swarm.peers would throw an uncaught error
if any peer in the reponse could have its peerId or multiaddr validated.

This PR catches errors that occur while validating the peer info. The
returned array will contain an entry for every peer in the ipfs response.
peer-info objects that couldn't be validated, now have an `error` property
and a `rawPeerInfo` property. This at least means the count of peers in
the response will be accurate, and there the info is available to the caller.

This means that callers now have to deal with peer-info objects that may
not have a `peer or `addr` property.

Adds `nock` tests to exercice the code under different error conditions.
Doing so uncovered a bug in our legacy go-ipfs <= 0.4.4 peer info parsing,
which is also fixed. The code was trying to decapusalate the peerId from
the multiaddr, but doing so trims the peerId rather than returning it.

fixes #885

License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

2018-11-06 17:16 UTC, olizilla commented
This also fixes https://github.com/ipfs-shipyard/ipfs-webui/issues/878

2018-11-07 11:11 UTC, diasdavid commented
Remove the `.spec` from the filename and add a node.js file that has a `require` for those tests. See https://github.com/ipfs/js-ipfs/blob/master/test/core/node.js for example

2018-11-09 09:11 UTC, alanshaw requested changes
Code LGTM. Do you have a moment to PR https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/SWARM.md#swarmpeers to make a note of the change?

2018-11-09 10:16 UTC, olizilla commented
@alanshaw related to our conversations about the multiaddr validation problem, I found this https://github.com/multiformats/multiaddr/issues/70

2018-11-13 11:18 UTC, olizilla commented
The [`codelint`](https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs-api/detail/PR-887/4/pipeline/268#step-293-log-9) and [`linux/8.12/test:node`](https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs-api/detail/PR-887/4/pipeline/361#step-491-log-122) CI failures are unrelated to this PR

There is a PR to update the interface-core spec here https://github.com/ipfs/interface-ipfs-core/pull/393

2018-11-26 11:26 UTC, alanshaw approved these changes

2018-11-26 12:05 UTC, merged